# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 09:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [(b'main', '0001_initial'), (b'main', '0002_auto_20160813_1021'), (b'main', '0003_auto_20160813_1025'), (b'main', '0004_auto_20160813_2032')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Proposal Title', max_length=512)),
                ('text', models.TextField(default=b'Proposal text', max_length=20000)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ValidUser',
            fields=[
                ('idcard', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Proposal Title', max_length=512)),
                ('nb_pro_votes', models.IntegerField(default=0)),
                ('nb_con_votes', models.IntegerField(default=0)),
                ('nb_blank_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('total_available_voters', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Votation_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Votation_modified_by', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Proposal')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='authors',
            field=models.ManyToManyField(to=b'main.ValidUser'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proposal_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proposal_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='validuser',
            unique_together=set([('user', 'idcard')]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 8, 21, 58, 168000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 8, 21, 58, 168000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
